### ISSUE TITLE
Enroll all Sandbox demo origin(s)

### ISSUE THREAD

**Issue by dmdabbs** [privacysandbox/privacy-sandbox-demos#77]
Really appreciate your creating a home for (web) Sandbox demos. Great for new developers looking to learn in the wake of the recent GA release. 

Suggest migrating other demo sites to enroll-able domains (i.e. from *.glitch.me) and ensuring they are [enrolled](https://github.com/privacysandbox/attestation):

> **Enrollment becomes a requirement in August 2023, and from that point on you won't be able to call the APIs until you have successfully completed the enrollment and attestation process.**

For example,
https://shared-storage-demo.web.app/
https://fledge-reporting-component-auction.glitch.me/
https://fledge-multi-seller-with-gpt.glitch.me/
https://topics-demo.glitch.me/ (and related)
https://private-state-token-demo.glitch.me/

**Comment by Seburan** [comment]
Hello David,

Thank you very much for your suggestion.

We are now working on getting the demo sites enrolled. 

For local testing we expect developers to use [Chrome flag](https://developer.chrome.com/blog/privacy-sandbox-launch/#enrollment) to bypass enrollment.

as you probably know the enrollment enforcement scheduled has [recently changed](https://github.com/privacysandbox/attestation/blob/main/how-to-enroll.md) to Chrome 118 so you should be able to continue using the demo throughout August even though we have not enrolled yet.

**Comment by dmdabbs** [comment]
If they are all on *.web.dev then it should be one enrollment fo that site. 

Arigato,
David
